# Generated by Django 4.2 on 2023-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(to='ingredients.ingredient', verbose_name='ingredient'),
        ),
    ]
