# Generated by Django 4.2 on 2023-04-06 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('products', '0003_product_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.CharField(max_length=256, verbose_name='qrcode_id')),
                ('amount', models.SmallIntegerField(verbose_name='amount')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_products', to='baskets.basket', verbose_name='basket_products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_basket', to='products.product', verbose_name='product_basket')),
            ],
            options={
                'verbose_name': 'Products in baskets',
            },
        ),
    ]
